import type { Metadata } from 'next';
import './globals.css';
import { SidebarProvider } from './context/SidebarContext';
import Sidebar from './components/sidebar/Sidebar';

export const metadata: Metadata = {
  title: 'Your Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <Sidebar />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}